API_KEY_OPENAI="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"
ACTIVE_COMPANY_ID=74